package com.pilarestilo.systemsettings.infrastructure.web.requests;

import jakarta.validation.constraints.Max;
import jakarta.validation.constraints.Min;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;
import jakarta.validation.constraints.DecimalMax;
import jakarta.validation.constraints.DecimalMin;

import java.util.List;

public record UpdateSystemSettingsRequest(
        @NotBlank @Size(max = 40) String whatsappNumber,
        @Size(max = 500) String instagramUrl,
        @Size(max = 500) String facebookUrl,
        @Size(max = 160) String bankTransferAccountHolder,
        @Size(max = 255) String bankTransferContactEmail,
        @Size(max = 120) String bankTransferAccountNumber,
        @Size(max = 120) String bankTransferBankName,
        @Size(max = 80) String bankTransferAccountType,
        @NotNull Boolean paymentMethodBankTransferEnabled,
        @NotNull Boolean paymentMethodGatewayEnabled,
        List<@NotBlank @Size(max = 40) String> paymentGatewayProviders,
        @Size(max = 255) String paymentGatewayMpApiBaseUrl,
        @Size(max = 500) String paymentGatewayMpSuccessUrl,
        @Size(max = 500) String paymentGatewayMpPendingUrl,
        @Size(max = 500) String paymentGatewayMpFailureUrl,
        @Size(max = 500) String paymentGatewayMpNotificationUrl,
        @Size(max = 255) String paymentGatewayMpAccessToken,
        Boolean clearPaymentGatewayMpAccessToken,
        @Size(max = 255) String paymentGatewayMpWebhookToken,
        Boolean clearPaymentGatewayMpWebhookToken,
        @NotBlank @Size(max = 40) String mediaStorageProvider,
        @Size(max = 255) String mediaS3Endpoint,
        @Size(max = 120) String mediaS3Region,
        @Size(max = 120) String mediaS3Bucket,
        @Size(max = 255) String mediaS3AccessKeyId,
        @Size(max = 255) String mediaS3SecretKey,
        Boolean clearMediaS3SecretKey,
        @NotNull Boolean mediaS3PathStyleEnabled,
        @Size(max = 500) String mediaS3PublicBaseUrl,
        @NotBlank @Size(max = 40) String notificationProvider,
        @Size(max = 500) String n8nWebhookUrl,
        @Size(max = 120) String n8nTokenHeaderName,
        @Size(max = 500) String n8nApiKey,
        Boolean clearN8nApiKey,
        @Size(max = 40) String whatsappSimulatedTo,
        @Size(max = 120) String whatsappSimulatedSender,
        @Size(max = 255) String whatsappTwilioApiBaseUrl,
        @Size(max = 255) String whatsappTwilioAccountSid,
        @Size(max = 80) String whatsappTwilioFrom,
        @Size(max = 80) String whatsappTwilioToFallback,
        @Size(max = 120) String whatsappTwilioSenderAlias,
        @Size(max = 255) String whatsappTwilioAuthToken,
        Boolean clearWhatsappTwilioAuthToken,
        @Size(max = 255) String sendgridApiBaseUrl,
        @Size(max = 255) String sendgridFromEmail,
        @Size(max = 120) String sendgridSenderName,
        @Size(max = 255) String sendgridToFallback,
        @Size(max = 255) String sendgridApiKey,
        Boolean clearSendgridApiKey,
        @Size(max = 120) String productAiInferDefaultBrand,
        @Size(max = 10) String productAiInferDefaultCondition,
        @Min(1000) Integer productAiInferBasePrice,
        @DecimalMin("1.00") @DecimalMax("5.00") java.math.BigDecimal productAiInferListPriceMultiplier,
        @Size(max = 255) String smtpHost,
        @Min(1) @Max(65535) Integer smtpPort,
        @Size(max = 255) String smtpUsername,
        @Size(max = 255) String smtpFromEmail,
        @Size(max = 255) String smtpPassword,
        Boolean clearSmtpPassword,
        @NotNull Boolean smtpAuthEnabled,
        @NotNull Boolean smtpStarttlsEnabled,
        String shippingZonesJson,
        String shippingCouriersJson,
        @Size(max = 32) String shippingPaymentMode,
        Boolean bankTransferAutoCancelEnabled,
        @Min(5) @Max(1440) Integer bankTransferAutoCancelTimeoutMinutes,
        @Size(max = 64) String bankTransferAutoCancelCron,
        @Size(max = 20) String taxPayerRut,
        @Size(max = 160) String taxBusinessName,
        @Size(max = 160) String taxBusinessActivity,
        @Size(max = 20) String taxActecoCode,
        @Size(max = 200) String taxAddress,
        @Size(max = 120) String taxCommune,
        @Size(max = 120) String taxCity,
        @DecimalMin("0.00") @DecimalMax("100.00") java.math.BigDecimal taxVatRate,
        Boolean taxDocumentRequiredBeforeDispatch,
        @Size(max = 30) String taxDocumentProvider
) {}
