ALTER TABLE categories ADD COLUMN menu_visible BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE categories ADD COLUMN category_type VARCHAR(24) NOT NULL DEFAULT 'GENERIC';
ALTER TABLE categories ADD COLUMN hero_image_url VARCHAR(500);
