INSERT INTO permissions (code, name, description, module, category) VALUES
    ('dashboard.read', 'Ver dashboard', 'Acceso al dashboard administrativo', 'analytics', 'read'),
    ('analytics.read', 'Ver analitica', 'Acceso a metricas y resumenes', 'analytics', 'read'),
    ('products.read', 'Ver productos', 'Listar y ver productos', 'products', 'read'),
    ('products.create', 'Crear productos', 'Crear productos nuevos', 'products', 'write'),
    ('products.update', 'Editar productos', 'Actualizar productos existentes', 'products', 'write'),
    ('products.delete', 'Eliminar productos', 'Eliminar productos', 'products', 'admin'),
    ('categories.read', 'Ver categorias', 'Listar y ver categorias', 'products', 'read'),
    ('categories.update', 'Editar categorias', 'Crear y editar categorias', 'products', 'write'),
    ('navigation.read', 'Ver navegacion', 'Ver menu y estructura editorial', 'products', 'read'),
    ('navigation.update', 'Editar navegacion', 'Editar menu y secciones', 'products', 'write'),
    ('reviews.read', 'Ver resenas', 'Listar resenas', 'products', 'read'),
    ('reviews.moderate', 'Moderar resenas', 'Aprobar, rechazar o editar resenas', 'products', 'workflow'),
    ('discounts.read', 'Ver descuentos', 'Listar descuentos', 'products', 'read'),
    ('discounts.update', 'Editar descuentos', 'Crear y editar descuentos', 'products', 'write'),
    ('publications.read', 'Ver publicaciones', 'Listar publicaciones comerciales', 'products', 'read'),
    ('publications.update', 'Editar publicaciones', 'Crear y editar publicaciones', 'products', 'write'),
    ('inventory.read', 'Ver inventario', 'Consultar inventario', 'inventory', 'read'),
    ('inventory.adjust', 'Ajustar inventario', 'Realizar movimientos de inventario', 'inventory', 'admin'),
    ('orders.read', 'Ver ordenes', 'Consultar ordenes', 'orders', 'read'),
    ('orders.update', 'Actualizar ordenes', 'Actualizar estado o datos de orden', 'orders', 'write'),
    ('payments.read', 'Ver pagos', 'Consultar pagos', 'cash', 'read'),
    ('payments.review', 'Revisar pagos', 'Revisar pagos manuales o pendientes', 'cash', 'workflow'),
    ('cash.read', 'Ver caja', 'Consultar caja', 'cash', 'read'),
    ('cash.open', 'Abrir caja', 'Abrir caja operativa', 'cash', 'workflow'),
    ('cash.close', 'Cerrar caja', 'Cerrar caja operativa', 'cash', 'workflow'),
    ('cash.adjust', 'Ajustar caja', 'Realizar ajustes de caja', 'cash', 'admin'),
    ('dispatch.read', 'Ver despachos', 'Consultar cola e historial de despachos', 'dispatch', 'read'),
    ('dispatch.claim', 'Tomar despachos', 'Tomar despachos pendientes', 'dispatch', 'workflow'),
    ('dispatch.manage', 'Gestionar despachos', 'Despachar, liberar y operar envios', 'dispatch', 'workflow'),
    ('dispatch.assign', 'Asignar despachos', 'Asignacion administrativa de despachos', 'dispatch', 'admin'),
    ('users.read', 'Ver usuarios', 'Consultar usuarios y trabajadores', 'users', 'read'),
    ('users.update', 'Editar usuarios', 'Editar usuarios y su estado', 'users', 'write'),
    ('users.assign_role', 'Asignar roles', 'Asignar o revocar rol laboral', 'users', 'admin'),
    ('roles.read', 'Ver roles y permisos', 'Consultar matriz RBAC', 'roles', 'read'),
    ('roles.manage', 'Gestionar roles y permisos', 'Modificar grants de permisos', 'roles', 'admin'),
    ('settings.read', 'Ver configuracion', 'Consultar configuracion de la tienda', 'settings', 'read'),
    ('settings.update', 'Editar configuracion', 'Modificar configuracion de la tienda', 'settings', 'write'),
    ('pos.read', 'Ver POS', 'Acceso general a POS', 'pos', 'read'),
    ('pos.sale.create', 'Crear venta POS', 'Registrar ventas en POS', 'pos', 'workflow'),
    ('pos.refund.create', 'Registrar devolucion POS', 'Registrar devoluciones en POS', 'pos', 'workflow')
ON CONFLICT (code) DO NOTHING;
