// Centralized icon exports. React islands import from here so the icon set
// stays consistent and tree-shakable. Astro components use Icon.astro instead.
export {
  ShoppingBag,
  ShoppingCart,
  Search,
  Heart,
  User,
  ChevronDown,
  ChevronRight,
  ChevronLeft,
  Star,
  Filter,
  X,
  Trash2,
  Edit3,
  Plus,
  Minus,
  Check,
  ArrowRight,
  ArrowLeft,
  LogOut,
  LogIn,
  Mail,
  Lock,
  Eye,
  EyeOff,
  Package,
  CreditCard,
  Tag,
  Layers,
  MessageSquare,
  Users,
  LayoutDashboard,
  Menu,
  Settings,
  AlertCircle,
  CheckCircle2,
  Loader2,
  Instagram,
  Facebook,
  Send,
  ImageIcon,
} from 'lucide-react';
